# Generated by Django 5.2.17 on 2026-09-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.BooleanField(default=False)),
                ('iit_project', models.BooleanField(default=False)),
                ('stock_update', models.BooleanField(default=False)),
                ('current_stock', models.BooleanField(default=False)),
                ('stock_report', models.BooleanField(default=False)),
                ('attendance', models.BooleanField(default=False)),
                ('daily_works', models.BooleanField(default=False)),
                ('user_management', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
