# Generated by Django 5.2.17 on 2026-08-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('SUPERVISOR', 'Supervisor'), ('LABOUR', 'Labour')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('project', models.CharField(default='IIT Project', max_length=200)),
                ('status', models.CharField(choices=[('WORKED', 'Worked'), ('NOT_WORKED', 'Not Worked')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date', 'project'), name='unique_employee_date_project')],
            },
        ),
    ]
